### ISSUE TITLE
Tagged Releases

### ISSUE THREAD

**Issue by damianoneill** [joe-speedboat/ansible.ospatch#2]
Hi @joe-speedboat thanks for providing the role. 

Would it be possible to tag the repo so that you could version on ansible-galaxy other than HEAD?  

Thanks,
Damian.

**Comment by joe-speedboat** [comment]
oh, sorry for the delay /-)
Sure, I will create tag, release and branch.
BR chris

**Comment by joe-speedboat** [comment]
done
